# Generated by Django 5.0.4 on 2024-07-24 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0007_subject_subjectmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectmark',
            options={'ordering': ['student']},
        ),
    ]
