# Generated by Django 5.0.4 on 2024-07-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggie', '0010_recipe_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
